In [1]:
import numpy as np

In [2]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [4]:
x = np.random.randn(10)
x

array([ 0.98291791, -0.64980027, -0.85528046,  2.77751894,  0.93437622,
        0.44150286,  0.63007041,  1.01170163, -0.14753544, -0.62731804])

In [5]:
y = np.random.rand(10)
y

array([0.55181059, 0.08933946, 0.87698261, 0.76861703, 0.32433321,
       0.08919409, 0.22519859, 0.34395552, 0.28210731, 0.33220127])

In [6]:
np.maximum(x, y)

array([0.98291791, 0.08933946, 0.87698261, 2.77751894, 0.93437622,
       0.44150286, 0.63007041, 1.01170163, 0.28210731, 0.33220127])

In [7]:
arr2 = np.random.randn(6, 5)
arr2

array([[-0.19545901, -1.12069004,  0.89343461, -0.64441317, -1.05159373],
       [ 0.1211482 , -0.24432176, -2.68037782, -1.11759068,  2.80849089],
       [-0.04980593, -0.03310895,  1.03601552,  0.04419547, -0.58865097],
       [ 0.74209653, -0.68493358,  0.48057218,  2.32407939,  0.40082411],
       [-0.67555357, -0.0671608 , -0.10259865, -0.04086257,  0.83777922],
       [-0.22227979, -0.30857442,  0.71830343, -1.4529625 ,  1.40108236]])

In [8]:
arr2.sum()

0.5270839309215062

In [9]:
arr2.mean()

0.017569464364050207

In [11]:
arr2.sum(axis=0)

array([-0.27985357, -2.45878956,  0.34534926, -0.88755407,  3.80793187])

In [12]:
arr2.sum(axis=1)

array([-2.11872134, -1.11265118,  0.40864512,  3.26263863, -0.04839636,
        0.13556906])

In [13]:
(arr2 > 0).sum()

12

In [14]:
arr2 > 0

array([[False, False,  True, False, False],
       [ True, False, False, False,  True],
       [False, False,  True,  True, False],
       [ True, False,  True,  True,  True],
       [False, False, False, False,  True],
       [False, False,  True, False,  True]])

In [15]:
arr3 = np.random.randn(7)
arr3

array([-1.20224511,  0.39505544,  0.75763856,  0.08393129, -0.56784168,
        1.4129242 , -1.6010011 ])

In [18]:
arr3.sort()
arr3

array([-1.6010011 , -1.20224511, -0.56784168,  0.08393129,  0.39505544,
        0.75763856,  1.4129242 ])

In [19]:
arr4 = np.random.randn(5, 3)

In [20]:
arr4

array([[-0.32321978,  0.14193879, -0.39518805],
       [ 0.54076871,  0.67442273, -0.08635867],
       [-0.61723787,  0.69926028,  2.13040664],
       [ 0.58506235,  0.65958347,  0.56635337],
       [-0.54830751, -0.46314826,  1.04229424]])

In [21]:
np.sort(arr4, axis=0)

array([[-0.61723787, -0.46314826, -0.39518805],
       [-0.54830751,  0.14193879, -0.08635867],
       [-0.32321978,  0.65958347,  0.56635337],
       [ 0.54076871,  0.67442273,  1.04229424],
       [ 0.58506235,  0.69926028,  2.13040664]])

In [23]:
np.sort(arr4, axis=1)

array([[-0.39518805, -0.32321978,  0.14193879],
       [-0.08635867,  0.54076871,  0.67442273],
       [-0.61723787,  0.69926028,  2.13040664],
       [ 0.56635337,  0.58506235,  0.65958347],
       [-0.54830751, -0.46314826,  1.04229424]])

In [24]:
np.sort(arr4, axis=1)[::-1]

array([[-0.54830751, -0.46314826,  1.04229424],
       [ 0.56635337,  0.58506235,  0.65958347],
       [-0.61723787,  0.69926028,  2.13040664],
       [-0.08635867,  0.54076871,  0.67442273],
       [-0.39518805, -0.32321978,  0.14193879]])

In [25]:
value = np.array([1, 2, 2, 3, 3, 4, 1, 3, 5])

In [26]:
np.unique(value)

array([1, 2, 3, 4, 5])