In [1]:
import numpy as np

In [2]:
data1 = [10, 9.9, 10, 9.8, 20]

In [3]:
type(data1)

list

In [6]:
arr1 = np.array(data1)

In [7]:
type(arr1)

numpy.ndarray

In [8]:
data1

[10, 9.9, 10, 9.8, 20]

In [9]:
arr1

array([10. ,  9.9, 10. ,  9.8, 20. ])

In [10]:
arr1.shape

(5,)

In [11]:
np.zeros((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [13]:
np.ones(3)

array([1., 1., 1.])

In [15]:
np.ones((3, 7))

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [16]:
data2 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [17]:
data2

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [18]:
type(data2)

list

In [19]:
arr2 = np.array(data2)

In [20]:
type(arr2)

numpy.ndarray

In [21]:
arr1.dtype

dtype('float64')

In [22]:
arr2.dtype

dtype('int32')

In [23]:
# np.arange?

In [24]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
arr3 = np.array([1, 2, 3, 4, 5], dtype=np.int64)

In [26]:
arr3

array([1, 2, 3, 4, 5], dtype=int64)

In [29]:
arr3.dtype

dtype('int64')

In [30]:
float_arr3 = arr3.astype(np.float64)

In [31]:
float_arr3.dtype

dtype('float64')

In [32]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.float64)

In [33]:
arr2 = np.array([[7, 8, 9], [10, 11, 12]], dtype=np.float64)

In [34]:
arr1

array([[1., 2., 3.],
       [4., 5., 6.]])

In [35]:
arr2

array([[ 7.,  8.,  9.],
       [10., 11., 12.]])

In [36]:
arr1 + arr2

array([[ 8., 10., 12.],
       [14., 16., 18.]])

In [37]:
arr1 * arr2

array([[ 7., 16., 27.],
       [40., 55., 72.]])

In [38]:
arr1 * 2

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

In [39]:
arr1 ** 2

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [40]:
arr1 ** 3

array([[  1.,   8.,  27.],
       [ 64., 125., 216.]])

In [41]:
names = np.array(['somang', 'bu-heung', 'pyeong-gang', 'young-gwang', 'umma', 'boguem', 'haum'])

In [42]:
data = np.random.randn(7, 4)

In [43]:
data

array([[-0.31594094,  1.15460183,  0.04746117, -0.21911927],
       [ 0.11162483,  1.37192533, -1.41089353, -0.1389107 ],
       [ 0.06398541,  0.66151933, -0.80679633,  1.72395011],
       [ 0.68117367, -0.56456756,  1.10987419,  0.92317086],
       [-0.55315751,  0.79062308,  2.0228604 , -0.46868574],
       [-0.80659247, -0.63191401, -0.51394536, -0.02557759],
       [-0.6973742 ,  0.36399355,  1.46496272, -1.88370975]])

In [44]:
type(names)

numpy.ndarray

In [45]:
type(data)

numpy.ndarray

In [46]:
names.dtype

dtype('<U11')

In [47]:
names

array(['somang', 'bu-heung', 'pyeong-gang', 'young-gwang', 'umma',
       'boguem', 'haum'], dtype='<U11')

In [48]:
data

array([[-0.31594094,  1.15460183,  0.04746117, -0.21911927],
       [ 0.11162483,  1.37192533, -1.41089353, -0.1389107 ],
       [ 0.06398541,  0.66151933, -0.80679633,  1.72395011],
       [ 0.68117367, -0.56456756,  1.10987419,  0.92317086],
       [-0.55315751,  0.79062308,  2.0228604 , -0.46868574],
       [-0.80659247, -0.63191401, -0.51394536, -0.02557759],
       [-0.6973742 ,  0.36399355,  1.46496272, -1.88370975]])

In [49]:
names == 'somang'

array([ True, False, False, False, False, False, False])

In [51]:
data[names == 'umma', :]

array([[-0.55315751,  0.79062308,  2.0228604 , -0.46868574]])

In [57]:
data[(names == 'somang') | (names == 'haum')]

array([[-0.31594094,  1.15460183,  0.04746117, -0.21911927],
       [-0.6973742 ,  0.36399355,  1.46496272, -1.88370975]])

In [58]:
data[:, 3]

array([-0.21911927, -0.1389107 ,  1.72395011,  0.92317086, -0.46868574,
       -0.02557759, -1.88370975])

In [59]:
data[:, 3] < 0

array([ True,  True, False, False,  True,  True,  True])

In [60]:
data[data[:, 3] < 0, 3] = 0

In [61]:
data

array([[-0.31594094,  1.15460183,  0.04746117,  0.        ],
       [ 0.11162483,  1.37192533, -1.41089353,  0.        ],
       [ 0.06398541,  0.66151933, -0.80679633,  1.72395011],
       [ 0.68117367, -0.56456756,  1.10987419,  0.92317086],
       [-0.55315751,  0.79062308,  2.0228604 ,  0.        ],
       [-0.80659247, -0.63191401, -0.51394536,  0.        ],
       [-0.6973742 ,  0.36399355,  1.46496272,  0.        ]])

In [62]:
a = [1, 2, 3]
b = [1, 2, 3]

In [63]:
print(a + b)

[1, 2, 3, 1, 2, 3]


In [65]:
c = np.array([[1, 2, 3]])
d = np.array([[4, 5, 6]])

In [66]:
print(c + d)

[[5 7 9]]


In [67]:
type(c)

numpy.ndarray

In [70]:
arr = np.array([1, 2, 3, 4, 5])

In [71]:
arr * 2

array([ 2,  4,  6,  8, 10])

In [75]:
# c = np.array([[1, 2, 3]])
# d = np.array([[4, 5, 6, 7]])
# print(c + d)

ValueError: operands could not be broadcast together with shapes (1,3) (1,4) 