In [1]:
import numpy as np

In [2]:
data1 = [10, 9.9, 10, 9.8, 20] 

In [3]:
type(data1)

list

In [5]:
#np.array?

In [6]:
arr1 = np.array(data1)

In [7]:
type(arr1)

numpy.ndarray

In [9]:
data1

[10, 9.9, 10, 9.8, 20]

In [10]:
arr1

array([10. ,  9.9, 10. ,  9.8, 20. ])

In [11]:
arr1.shape

(5,)

In [12]:
np.zeros((3,5)) 

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [14]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [15]:
np.ones((3,7)) 

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [16]:
data2 = [ [1,2,3], [4,5,6], [7,8,9] ] 

In [17]:
data2

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [18]:
type(data2)

list

In [19]:
arr2 = np.array(data2)

In [20]:
type(arr2)

numpy.ndarray

In [21]:
arr1.dtype

dtype('float64')

In [22]:
arr2.dtype

dtype('int32')

In [23]:
#np.arange?

In [24]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
arr = np.array([1,2,3,4,5], dtype=np.int64) 

In [26]:
arr.dtype

dtype('int64')

In [27]:
float_arr = arr.astype(np.float64)

In [28]:
float_arr

array([1., 2., 3., 4., 5.])

In [29]:
float_arr.dtype

dtype('float64')

In [30]:
arr1  = np.array([[1,2,3],[4,5,6]], dtype=np.float64)

In [31]:
arr2  = np.array([[7,8,9],[10,11,12]], dtype=np.float64)

In [32]:
arr1

array([[1., 2., 3.],
       [4., 5., 6.]])

In [33]:
arr2

array([[ 7.,  8.,  9.],
       [10., 11., 12.]])

In [34]:
arr1 + arr2

array([[ 8., 10., 12.],
       [14., 16., 18.]])

In [35]:
arr1 * arr2

array([[ 7., 16., 27.],
       [40., 55., 72.]])

In [36]:
arr1

array([[1., 2., 3.],
       [4., 5., 6.]])

In [37]:
arr1 * 2

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

In [38]:
arr1 ** 2

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [39]:
names = np.array(['pyo','sunyoung','psy','pyo','sunyoung','sunny','sunyoung'])

In [40]:
data = np.random.randn(7,4) 

In [41]:
type(names)

numpy.ndarray

In [42]:
type(data)

numpy.ndarray

In [43]:
names

array(['pyo', 'sunyoung', 'psy', 'pyo', 'sunyoung', 'sunny', 'sunyoung'],
      dtype='<U8')

In [44]:
data

array([[-1.17835187,  1.60348402, -0.87879036,  0.71329245],
       [ 0.68182015, -0.28261048, -0.80402609,  0.73649052],
       [-0.42439682,  0.18345444, -0.9496866 , -1.24913355],
       [-0.41024477, -0.52960253, -0.2093219 , -1.13754685],
       [-1.89233987, -0.28718294, -0.19488092, -1.14858369],
       [ 0.19846854,  2.58966735, -0.57458332, -0.83073252],
       [ 0.67187771,  0.18444435, -0.62350591,  0.81598819]])

In [45]:
names == 'sunyoung'

array([False,  True, False, False,  True, False,  True])

In [46]:
data[ names =='sunyoung', : ] 

array([[ 0.68182015, -0.28261048, -0.80402609,  0.73649052],
       [-1.89233987, -0.28718294, -0.19488092, -1.14858369],
       [ 0.67187771,  0.18444435, -0.62350591,  0.81598819]])

In [47]:
data[ names =='pyo', : ] 

array([[-1.17835187,  1.60348402, -0.87879036,  0.71329245],
       [-0.41024477, -0.52960253, -0.2093219 , -1.13754685]])

In [48]:
data[ (names =='sunyoung') | (names == 'pyo') ]  

array([[-1.17835187,  1.60348402, -0.87879036,  0.71329245],
       [ 0.68182015, -0.28261048, -0.80402609,  0.73649052],
       [-0.41024477, -0.52960253, -0.2093219 , -1.13754685],
       [-1.89233987, -0.28718294, -0.19488092, -1.14858369],
       [ 0.67187771,  0.18444435, -0.62350591,  0.81598819]])

In [49]:
data [ : , 3] 

array([ 0.71329245,  0.73649052, -1.24913355, -1.13754685, -1.14858369,
       -0.83073252,  0.81598819])

In [50]:
data

array([[-1.17835187,  1.60348402, -0.87879036,  0.71329245],
       [ 0.68182015, -0.28261048, -0.80402609,  0.73649052],
       [-0.42439682,  0.18345444, -0.9496866 , -1.24913355],
       [-0.41024477, -0.52960253, -0.2093219 , -1.13754685],
       [-1.89233987, -0.28718294, -0.19488092, -1.14858369],
       [ 0.19846854,  2.58966735, -0.57458332, -0.83073252],
       [ 0.67187771,  0.18444435, -0.62350591,  0.81598819]])

In [51]:
data [ : , 3] < 0 

array([False, False,  True,  True,  True,  True, False])

In [52]:
data[ data [ : , 3] < 0 , : ]

array([[-0.42439682,  0.18345444, -0.9496866 , -1.24913355],
       [-0.41024477, -0.52960253, -0.2093219 , -1.13754685],
       [-1.89233987, -0.28718294, -0.19488092, -1.14858369],
       [ 0.19846854,  2.58966735, -0.57458332, -0.83073252]])

In [53]:
data[ data [ : , 3] < 0 , 3 ]

array([-1.24913355, -1.13754685, -1.14858369, -0.83073252])

In [54]:
data

array([[-1.17835187,  1.60348402, -0.87879036,  0.71329245],
       [ 0.68182015, -0.28261048, -0.80402609,  0.73649052],
       [-0.42439682,  0.18345444, -0.9496866 , -1.24913355],
       [-0.41024477, -0.52960253, -0.2093219 , -1.13754685],
       [-1.89233987, -0.28718294, -0.19488092, -1.14858369],
       [ 0.19846854,  2.58966735, -0.57458332, -0.83073252],
       [ 0.67187771,  0.18444435, -0.62350591,  0.81598819]])

In [55]:
data[ data [ : , 3] < 0 , 3 ] = 0

In [56]:
data

array([[-1.17835187,  1.60348402, -0.87879036,  0.71329245],
       [ 0.68182015, -0.28261048, -0.80402609,  0.73649052],
       [-0.42439682,  0.18345444, -0.9496866 ,  0.        ],
       [-0.41024477, -0.52960253, -0.2093219 ,  0.        ],
       [-1.89233987, -0.28718294, -0.19488092,  0.        ],
       [ 0.19846854,  2.58966735, -0.57458332,  0.        ],
       [ 0.67187771,  0.18444435, -0.62350591,  0.81598819]])

In [57]:
a = [1,2,3] 
b = [1,2,3]

In [58]:
print(a+b)

[1, 2, 3, 1, 2, 3]


In [59]:
c = np.array([1,2,3])
d = np.array([4,5,6]) 

In [60]:
print(c+d)

[5 7 9]


In [61]:
arr = np.array([1,2,3,4,5]) 

In [62]:
arr * 2

array([ 2,  4,  6,  8, 10])

In [63]:
c = np.array([1,2,3])
d = np.array([4,5,6,7]) 

In [66]:
# ValueError: operands could not be broadcast together with shapes (3,) (4,) 
#print(c+d)