In [1]:
import numpy as np

In [2]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
#np.sqrt?

In [4]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [5]:
x = np.random.rand(10) 
x

array([0.75944393, 0.28881275, 0.01510485, 0.93128245, 0.13977427,
       0.37658925, 0.76244567, 0.9431642 , 0.52722126, 0.98073858])

In [6]:
y = np.random.rand(10)

In [7]:
y

array([0.87827196, 0.18000242, 0.88177324, 0.48888879, 0.53373901,
       0.66199943, 0.38972573, 0.34994824, 0.48081748, 0.98647844])

In [8]:
np.maximum(x,y)

array([0.87827196, 0.28881275, 0.88177324, 0.93128245, 0.53373901,
       0.66199943, 0.76244567, 0.9431642 , 0.52722126, 0.98647844])

In [9]:
arr2 = np.random.randn(6,5) 
arr2

array([[ 0.21825096,  1.71710358, -0.19634272, -1.45301263,  0.29357862],
       [-0.23693414, -1.81955032, -1.21782818, -0.43148551,  1.76019695],
       [ 2.08278334,  1.6074812 , -0.57846442, -0.60726775, -0.78502731],
       [-0.69668524, -1.08518453,  1.47362061,  0.9182478 ,  1.00736535],
       [ 0.74126539,  0.18275817, -0.90538369,  0.82875624, -0.22625051],
       [ 0.14931697, -0.82479774,  2.0221187 , -0.44679736, -0.59457909]])

In [10]:
arr2.sum() 

2.8972527344979206

In [11]:
arr2.mean() 

0.0965750911499307

In [12]:
arr2.sum(axis=0) 

array([ 2.25799727, -0.22218964,  0.5977203 , -1.19155921,  1.45528401])

In [13]:
arr2.sum(axis=1) 

array([ 0.5795778 , -1.9456012 ,  1.71950506,  1.61736399,  0.62114561,
        0.30526148])

In [14]:
arr2

array([[ 0.21825096,  1.71710358, -0.19634272, -1.45301263,  0.29357862],
       [-0.23693414, -1.81955032, -1.21782818, -0.43148551,  1.76019695],
       [ 2.08278334,  1.6074812 , -0.57846442, -0.60726775, -0.78502731],
       [-0.69668524, -1.08518453,  1.47362061,  0.9182478 ,  1.00736535],
       [ 0.74126539,  0.18275817, -0.90538369,  0.82875624, -0.22625051],
       [ 0.14931697, -0.82479774,  2.0221187 , -0.44679736, -0.59457909]])

In [15]:
(arr2 > 0 ).sum()

14

In [16]:
arr2 > 0

array([[ True,  True, False, False,  True],
       [False, False, False, False,  True],
       [ True,  True, False, False, False],
       [False, False,  True,  True,  True],
       [ True,  True, False,  True, False],
       [ True, False,  True, False, False]])

In [19]:
arr2 < 0

array([[False, False,  True,  True, False],
       [ True,  True,  True,  True, False],
       [False, False,  True,  True,  True],
       [ True,  True, False, False, False],
       [False, False,  True, False,  True],
       [False,  True, False,  True,  True]])

In [20]:
(arr2 < 0).sum()

16

In [21]:
arr3 = np.random.randn(7) 

In [22]:
arr3

array([ 1.30562879,  0.26992113, -0.78185904, -0.22155486,  0.33721254,
        0.54148744, -0.29807359])

In [23]:
arr3.sort()

In [24]:
arr3

array([-0.78185904, -0.29807359, -0.22155486,  0.26992113,  0.33721254,
        0.54148744,  1.30562879])

In [25]:
arr4 = np.random.randn(5,3) 
arr4

array([[ 2.34714329,  0.21123129, -0.5992706 ],
       [-0.89668763,  0.83004815,  1.19138643],
       [ 0.59110797,  1.32950205,  1.86495937],
       [-0.96746073, -1.64528407, -0.38300034],
       [ 0.45670556,  1.32801257, -0.65040464]])

In [27]:
np.sort(arr4, axis=0) 

array([[-0.96746073, -1.64528407, -0.65040464],
       [-0.89668763,  0.21123129, -0.5992706 ],
       [ 0.45670556,  0.83004815, -0.38300034],
       [ 0.59110797,  1.32801257,  1.19138643],
       [ 2.34714329,  1.32950205,  1.86495937]])

In [28]:
np.sort(arr4, axis=1) 

array([[-0.5992706 ,  0.21123129,  2.34714329],
       [-0.89668763,  0.83004815,  1.19138643],
       [ 0.59110797,  1.32950205,  1.86495937],
       [-1.64528407, -0.96746073, -0.38300034],
       [-0.65040464,  0.45670556,  1.32801257]])

In [29]:
arr4.sort(axis=0)

In [30]:
arr4

array([[-0.96746073, -1.64528407, -0.65040464],
       [-0.89668763,  0.21123129, -0.5992706 ],
       [ 0.45670556,  0.83004815, -0.38300034],
       [ 0.59110797,  1.32801257,  1.19138643],
       [ 2.34714329,  1.32950205,  1.86495937]])

In [31]:
np.sort(arr4, axis=0) 

array([[-0.96746073, -1.64528407, -0.65040464],
       [-0.89668763,  0.21123129, -0.5992706 ],
       [ 0.45670556,  0.83004815, -0.38300034],
       [ 0.59110797,  1.32801257,  1.19138643],
       [ 2.34714329,  1.32950205,  1.86495937]])

In [32]:
np.sort(arr4, axis=0)[::-1] 

array([[ 2.34714329,  1.32950205,  1.86495937],
       [ 0.59110797,  1.32801257,  1.19138643],
       [ 0.45670556,  0.83004815, -0.38300034],
       [-0.89668763,  0.21123129, -0.5992706 ],
       [-0.96746073, -1.64528407, -0.65040464]])

In [33]:
value = np.array([1,2,2,3,3,4,1,3,5])

In [34]:
np.unique(value)

array([1, 2, 3, 4, 5])